### PR TITLE
Support for apple's mac m1.

### PR DESCRIPTION
**Pull request by Yaya48**
This pull request changes some little things to make m1 macs work.

### CODE REVIEW

**Comment by LukeZGD** [comment]
Some things:

1. Do not add custom IPSWs in the cleanup, they're up for the user to keep
2. Where is the iPwnder32 binary from? It is significantly smaller and does not match the one from the site of dora2ios

**Comment by Yaya48** [comment]
1) if I don't make custom ipsw to delete it doesnt remake the patched ibss and ibec so it will struggle when it goes to pwnedREC
2) i recompiled ipwnder from Dora to be universal.
3) yes

**Comment by LukeZGD** [comment]
Thanks, I will first test things on my end sometime later before merging the changes

**Comment by LukeZGD** [comment]
Thanks for the PR, I implemented this with 714a6fa expanding from the changes here

Also added note that I cannot support M1 if ever things break

**Pull request closed without merging**
